# Generated by Django 5.0.6 on 2026-09-29 22:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_servicio', models.CharField(choices=[('DOM_TRIBUTARIO', 'Domicilio Tributario'), ('DOM_COMERCIAL', 'Domicilio Comercial'), ('OF_VIRTUAL', 'Oficina Virtual Pro'), ('EMP_UN_DIA', 'Constitución Empresa en un Día'), ('OTRO', 'Otro Servicio')], default='DOM_TRIBUTARIO', max_length=30)),
                ('descripcion', models.TextField(verbose_name='Descripción de características')),
                ('precio_mensual', models.IntegerField(default=0, verbose_name='Precio Mensual (CLP)')),
                ('precio_anual', models.IntegerField(default=0, verbose_name='Precio Anual (CLP)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan / Servicio',
                'verbose_name_plural': 'Planes / Servicios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], default='JURIDICA', max_length=10)),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT / RUN')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social / Nombre Completo')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Fantasía')),
                ('giro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giro Comercial')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección Particular/Matriz')),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('rep_legal_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Rep. Legal')),
                ('rep_legal_rut', models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT Rep. Legal')),
                ('rep_legal_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Rep. Legal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ejecutivo_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo Asignado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Folio Contrato')),
                ('fecha_contratacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio del Servicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PENDIENTE_FIRMA', 'Pendiente de Firma'), ('ACTIVO', 'Activo'), ('POR_VENCER', 'Próximo a Vencer (Alerta)'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=20)),
                ('monto_pagado', models.IntegerField(default=0)),
                ('transaccion_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Pasarela de Pago')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones', to='servicios.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrataciones', to='servicios.plan')),
            ],
            options={
                'verbose_name': 'Contratación',
                'verbose_name_plural': 'Contrataciones',
                'ordering': ['-fecha_contratacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(default='Contrato Domicilio Tributario', max_length=100)),
                ('archivo_borrador', models.FileField(blank=True, null=True, upload_to='contratos/borradores/')),
                ('archivo_firmado', models.FileField(blank=True, null=True, upload_to='contratos/firmados/')),
                ('id_proceso_firma', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID API Firma')),
                ('estado_firma', models.CharField(choices=[('GENERADO', 'Documento Generado'), ('ENVIADO_FIRMA', 'Enviado a Firma Electrónica'), ('FIRMADO', 'Firmado Exitosamente'), ('RECHAZADO', 'Firma Rechazada/Error')], default='GENERADO', max_length=20)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('contratacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='servicios.contratacion')),
            ],
            options={
                'verbose_name': 'Documento / Contrato',
                'verbose_name_plural': 'Documentos / Contratos',
            },
        ),
    ]
